name: CI/CD Pipeline for Odoo 17

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2 
        with:
          python-version: '3.10'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y wget git python3-dev python3-pip build-essential libxslt1-dev libzip-dev libldap2-dev libsasl2-dev python3-setuptools node-less libjpeg-dev libpq-dev

      - name: Install wkhtmltopdf
        run: |
          wget https://github.com/wkhtmltopdf/wkhtmltopdf/releases/download/0.12.5/wkhtmltox_0.12.5-1.bionic_amd64.deb
          sudo apt install -y ./wkhtmltox_0.12.5-1.bionic_amd64.deb

      - name: Install Odoo dependencies
        run: |
          pip install wheel
          pip install cryptography
          pip install -r requirements.txt

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with: 
         ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          
      - name: Add SSH Known Hosts
        run: |
          ssh-keyscan -H 172.105.174.68 >> ~/.ssh/known_hosts

      - name: Deploy new module to Odoo server
        run: |
          scp -r addons/developer_mode root@172.105.174.68:/opt/odoo17/addons/
          scp -r addons/base_account_budget root@172.105.174.68:/opt/odoo17/addons/
          scp -r addons/base_accounting_kit root@172.105.174.68:/opt/odoo17/addons/
          scp -r addons/import_bank_statement_odoo root@172.105.174.68:/opt/odoo17/addons/
          scp -r addons/odoo_dynamic_dashboard root@172.105.174.68:/opt/odoo17/addons/
          scp -r addons/advance_cash_flow_statements root@172.105.174.68:/opt/odoo17/addons/
          scp -r addons/trial_balance_pdf root@172.105.174.68:/opt/odoo17/addons/
          scp -r addons/project_dashboard_odoo root@172.105.174.68:/opt/odoo17/addons/
          scp -r addons/projects_task_checklists root@172.105.174.68:/opt/odoo17/addons/
          scp -r addons/advanced_project_management_system root@172.105.174.68:/opt/odoo17/addons/
          scp -r addons/document_management_system root@172.105.174.68:/opt/odoo17/addons/
          scp -r addons/sh_base_document root@172.105.174.68:/opt/odoo17/addons/
          scp -r addons/account_move_multi_cancel root@172.105.174.68:/opt/odoo17/addons/
          scp -r addons/reset_journal_entries root@172.105.174.68:/opt/odoo17/addons/
          scp -r addons/invoice_merging root@172.105.174.68:/opt/odoo17/addons/
          scp -r addons/multiple_payment_for_outstanding_dues root@172.105.174.68:/opt/odoo17/addons/
          scp -r addons/contact_documents root@172.105.174.68:/opt/odoo17/addons/
          scp -r addons/openai_odoo_base root@172.105.174.68:/opt/odoo17/addons/
          scp -r addons/chatgpt_support_chatter root@172.105.174.68:/opt/odoo17/addons/
          scp -r addons/easy_chatgpt_access root@172.105.174.68:/opt/odoo17/addons/
          scp -r addons/contacts_birthday_greetings root@172.105.174.68:/opt/odoo17/addons/
          scp -r addons/partner_emails_history root@172.105.174.68:/opt/odoo17/addons/
          scp -r addons/schedule_activity_to_multiple_users root@172.105.174.68:/opt/odoo17/addons/
          scp -r addons/bi_sms_client_generic root@172.105.174.68:/opt/odoo17/addons/
          scp -r addons/whatsapp_mail_messaging root@172.105.174.68:/opt/odoo17/addons/
          scp -r addons/whatsapp_redirect root@172.105.174.68:/opt/odoo17/addons/
          scp -r addons/website_floating_whatsapp_icon root@172.105.174.68:/opt/odoo17/addons/
          scp -r addons/auto_daily_weekly_report root@172.105.174.68:/opt/odoo17/addons/
          scp -r addons/project_progress_bar root@172.105.174.68:/opt/odoo17/addons/
          scp -r addons/mail_push_notification root@172.105.174.68:/opt/odoo17/addons/
          scp -r addons/psql_query_execute root@172.105.174.68:/opt/odoo17/addons/
          scp -r addons/user_login_alert root@172.105.174.68:/opt/odoo17/addons/
          scp -r addons/size_restriction_for_attachments root@172.105.174.68:/opt/odoo17/addons/
          scp -r addons/base_advanced_report_templates root@172.105.174.68:/opt/odoo17/addons/





      - name: Install Python dependencies on Odoo server
        run: |
          ssh root@172.105.174.68 'pip3 install openpyxl qifparse pyfcm httpagentparser'

      - name: Run tests on Production Server
        run: |
          ssh root@172.105.174.68 'cd /opt/odoo17 && ./odoo-bin -c /etc/odoo17.conf --stop-after-init --test-enable --log-level=test'
